package com.tts.openWeatherApp;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
public class ZipCode {

	// Sets the Id as the Primary Key
	@Id
	// allows the Id to be generated by the underlying database
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	private String zip;
}
